---
- name: "INSTALL | PATCH | Import the MongoDB package signing key"
  ansible.builtin.rpm_key:
    key: "{{ mongodb8_cis_repo_gpgkey }}"
    state: present

- name: "INSTALL | PATCH | Add the official MongoDB Enterprise repository"
  ansible.builtin.yum_repository:
    name: "{{ mongodb8_cis_repo_name }}"
    description: MongoDB Enterprise Repository
    baseurl: "{{ mongodb8_cis_repo_baseurl }}"
    gpgkey: "{{ mongodb8_cis_repo_gpgkey }}"
    gpgcheck: true
    enabled: true

- name: "INSTALL | PATCH | Install MongoDB packages"
  ansible.builtin.dnf:
    name: "{{ mongodb8_cis_package }}"
    state: present

- name: "INSTALL | PATCH | Start and enable mongod"
  ansible.builtin.systemd_service:
    name: "{{ mongodb8_cis_service }}"
    state: started
    enabled: true
