---
- name: "5.1 | PATCH | Ensure that system activity is audited"
  when:
    - mongodb8_cis_rule_5_1
    - mongodb8_cis_level_1
    - mongodb8_cis_conf['auditLog'] is not defined   # an existing auditLog is kept as it is
  tags:
    - level1
    - automated
    - patch
    - rule_5.1
    - logging
  ansible.builtin.set_fact:
    mongodb8_cis_conf: "{{ mongodb8_cis_conf | combine({'auditLog': mongodb8_cis_audit_log}) }}"
    
