---
- name: "SECTION | 5.1 | Ensure that system activity is audited"
  ansible.builtin.import_tasks:
    file: cis_5.1.yml

- name: "SECTION | 5.2 | Ensure that audit filters are configured properly"
  ansible.builtin.import_tasks:
    file: cis_5.2.yml

- name: "SECTION | 5.3 | Ensure that logging captures as much information as possible"
  ansible.builtin.import_tasks:
    file: cis_5.3.yml

- name: "SECTION | 5.4 | Ensure that new entries are appended to the end of the log file"
  ansible.builtin.import_tasks:
    file: cis_5.4.yml
