---
- name: "SECTION | 3.1 | Ensure least privilege for database accounts"
  ansible.builtin.import_tasks:
    file: cis_3.1.yml

- name: "SECTION | 3.2 | Ensure that role-based access control is enabled and configured appropriately"
  ansible.builtin.import_tasks:
    file: cis_3.2.yml

- name: "SECTION | 3.3 | Ensure that MongoDB is run using a non-privileged, dedicated service account"
  ansible.builtin.import_tasks:
    file: cis_3.3.yml

- name: "SECTION | 3.4 | Ensure that each role for each MongoDB database is needed and grants only the necessary privileges"
  ansible.builtin.import_tasks:
    file: cis_3.4.yml

- name: "SECTION | 3.5 | Review Superuser/Admin Roles"
  ansible.builtin.import_tasks:
    file: cis_3.5.yml
